name: LeetCode Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # This runs the sync automatically every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: LeetCode Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          filter-duplicate-secs: 86400
          destination-folder: '.'
          verbose: true
          commit-header: 'Sync LeetCode submission'
